import { Card, ReactionEntry } from '@/types';

export const PH_COLOR_MAP = [
    { max: 1.0, color: '#DC2626', name: 'BAHAYA: x2.0 Dmg Asid!', effect: 'Bahaya Kakisan' },
    { max: 2.0, color: '#EF4444', name: 'AMARAN: x1.5 Dmg Asid!', effect: 'Kakisan Tinggi' },
    { max: 3.0, color: '#F97316', name: 'RISIKO: x1.25 Dmg Asid!', effect: 'Berasid' },
    { max: 5.0, color: '#FBBF24', name: 'Asid Lemah (x1.1 Dmg)', effect: 'Sedikit Berasid' },
    { max: 6.0, color: '#FDE047', name: 'Kurang Stabil', effect: 'Tiada Bonus/Malus' },
    { max: 8.0, color: '#22C55E', name: 'Stabil (+1 E / +1 M)', effect: 'Keseimbangan' },
    // Note: 7.0 is handled dynamically or falls into this range, but map uses 'max'. 
    // If logic finds <= 8 it picks this. We might need specific logic for 7.0 visual if relying purely on map.
    // However, existing logic (bonus resource) handles 7.0 specifically in code.
    // Let's refine for 7.0 if possible? The find logic usually takes first match.
    // If I put 7.0 before 8.0?
    // Let's insert 7.0 specific entry for UI sake?
    // Actually, `getPHDetails` likely iterates.
    { max: 9.0, color: '#86EFAC', name: 'Kurang Stabil', effect: 'Tiada Bonus/Malus' },
    { max: 11.0, color: '#60A5FA', name: 'Bes Lemah (x1.1 Dmg)', effect: 'Sedikit Beralkali' },
    { max: 12.0, color: '#3B82F6', name: 'RISIKO: x1.25 Dmg Bes!', effect: 'Beralkali' },
    { max: 13.0, color: '#6366F1', name: 'AMARAN: x1.5 Dmg Bes!', effect: 'Kaustik Tinggi' },
    { max: 14.0, color: '#A855F7', name: 'BAHAYA: x2.0 Dmg Bes!', effect: 'Bahaya Kaustik' },
];

export const REACTION_LIBRARY: ReactionEntry[] = [
    // --- HCl Reactions ---
    {
        attackerFormula: 'HCl',
        defenderFormula: 'NaOH',
        reactionName: '1.Extreme Neutralization',
        equation: 'HCl + NaOH → NaCl + H₂O',
        tcgEffect: 'Dapat Garam Dapur.',
        description: 'Peneutralan klasik Asid Kuat + Bes Kuat. Menghasilkan garam neutral (pH 7) yang penting untuk fungsi saraf dan otot manusia. Tiada lagi sifat kakisan!'
    },
    {
        attackerFormula: 'HCl',
        defenderFormula: 'NH₃',
        reactionName: '2.Salmiak Cloud',
        equation: 'HCl + NH₃ → NH₄Cl',
        tcgEffect: 'Dapat Salmiak (Buta).',
        description: 'Wap putih terbentuk apabila gas HCl bertemu ammonia! Menghasilkan garam berasid yang digunakan dalam bateri kering dan ubat batuk.'
    },
    {
        attackerFormula: 'HCl',
        defenderFormula: 'Mg(OH)₂',
        reactionName: '3.Magnesium Calm',
        equation: '2HCl + Mg(OH)₂ → MgCl₂ + 2H₂O',
        tcgEffect: 'Dapat Magnesium Klorida.',
        description: 'Reaksi ubat antasid! Meneutralkan asid perut yang berlebihan. Garam ini juga dikenali sebagai "Nigari" untuk membekukan tofu.'
    },
    {
        attackerFormula: 'HCl',
        defenderFormula: 'Al(OH)₃',
        reactionName: '4.Aluminum Barrier',
        equation: '3HCl + Al(OH)₃ → AlCl₃ + 3H₂O',
        tcgEffect: 'Dapat Aluminium Klorida.',
        description: 'Tindak balas dengan bes amfoterik. Garam yang terhasil digunakan dalam deodoran untuk menutup liang peluh (astringen).'
    },
    {
        attackerFormula: 'HCl',
        defenderFormula: 'Cu(OH)₂',
        reactionName: '5.Green Flame',
        equation: '2HCl + Cu(OH)₂ → CuCl₂ + 2H₂O',
        tcgEffect: 'Dapat Kuprum(II) Klorida.',
        description: 'Menghasilkan larutan hijau kebiruan yang cantik. Jika garam ini dibakar, ia menghasilkan nyalaan api berwarna hijau (Ujian Nyalaan)!'
    },
    // --- H2SO4 Reactions ---
    {
        attackerFormula: 'H₂SO₄',
        defenderFormula: 'NaOH',
        reactionName: '6.Exothermic Blast',
        equation: 'H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O',
        tcgEffect: 'Dapat Natrium Sulfat.',
        description: 'Tindak balas sangat eksotermik (membebaskan haba tinggi). Garam ini (Garam Glauber) digunakan dalam pembuatan detergen dan kaca.'
    },
    {
        attackerFormula: 'H₂SO₄',
        defenderFormula: 'NH₃',
        reactionName: '7.Fertilizer Boom',
        equation: 'H₂SO₄ + 2NH₃ → (NH₄)₂SO₄',
        tcgEffect: 'Dapat Ammonium Sulfat.',
        description: 'Penghasilan baja nitrogen yang penting untuk pertanian. Ia membekalkan nitrogen dan sulfur untuk pertumbuhan daun tumbuhan.'
    },
    {
        attackerFormula: 'H₂SO₄',
        defenderFormula: 'Mg(OH)₂',
        reactionName: '8.Epsom Synthesis',
        equation: 'H₂SO₄ + Mg(OH)₂ → MgSO₄ + 2H₂O',
        tcgEffect: 'Dapat Garam Epsom.',
        description: 'Menghasilkan Garam Epsom yang terkenal! Digunakan dalam mandian untuk melegakan otot yang sakit dan mengurangkan bengkak.'
    },
    {
        attackerFormula: 'H₂SO₄',
        defenderFormula: 'Al(OH)₃',
        reactionName: '9.Water Purifier',
        equation: '3H₂SO₄ + 2Al(OH)₃ → Al₂(SO₄)₃ + 6H₂O',
        tcgEffect: 'Dapat Aluminium Sulfat.',
        description: 'Garam ini digunakan dalam loji rawatan air sebagai agen penggumal (koagulan) untuk menjernihkan air yang keruh.'
    },
    {
        attackerFormula: 'H₂SO₄',
        defenderFormula: 'Cu(OH)₂',
        reactionName: '10.Blue Vitriol',
        equation: 'H₂SO₄ + Cu(OH)₂ → CuSO₄ + 2H₂O',
        tcgEffect: 'Dapat Vitriol Biru.',
        description: 'Penghabluran semula menghasilkan kristal biru "Blue Vitriol". Ia digunakan sebagai racun kulat (fungisid) dan algaecide di kolam.'
    },
    // --- HNO3 Reactions ---
    {
        attackerFormula: 'HNO₃',
        defenderFormula: 'NaOH',
        reactionName: '11.Nitrate Formation',
        equation: 'HNO₃ + NaOH → NaNO₃ + H₂O',
        tcgEffect: 'Dapat Natrium Nitrat.',
        description: 'Dikenali sebagai "Chile Saltpeter". Garam ini adalah pengoksida kuat yang digunakan dalam baja, bahan letupan, dan pengawet makanan.'
    },
    {
        attackerFormula: 'HNO₃',
        defenderFormula: 'NH₃',
        reactionName: '12.Explosive Mix',
        equation: 'HNO₃ + NH₃ → NH₄NO₃',
        tcgEffect: 'Dapat Ammonium Nitrat.',
        description: 'Garam dengan kandungan nitrogen tinggi. Stabil pada suhu bilik, tetapi boleh menjadi bahan letupan industri yang kuat jika dipanaskan!'
    },
    {
        attackerFormula: 'HNO₃',
        defenderFormula: 'Mg(OH)₂',
        reactionName: '13.Magnesium Nitrate',
        equation: '2HNO₃ + Mg(OH)₂ → Mg(NO₃)₂ + 2H₂O',
        tcgEffect: 'Dapat Magnesium Nitrat.',
        description: 'Garam yang sangat higroskopik (menyerap air dari udara). Digunakan sebagai baja dalam hidroponik dan agen pengering.'
    },
    {
        attackerFormula: 'HNO₃',
        defenderFormula: 'Al(OH)₃',
        reactionName: '14.Aluminum Nitrate',
        equation: '3HNO₃ + Al(OH)₃ → Al(NO₃)₃ + 3H₂O',
        tcgEffect: 'Dapat Aluminium Nitrat.',
        description: 'Ejen pengoksidaan kuat. Digunakan dalam penyamakan kulit dan penyediaan antipeluh, serta dalam makmal kimia.'
    },
    {
        attackerFormula: 'HNO₃',
        defenderFormula: 'Cu(OH)₂',
        reactionName: '15.Toxic Blue',
        equation: '2HNO₃ + Cu(OH)₂ → Cu(NO₃)₂ + 2H₂O',
        tcgEffect: 'Dapat Kuprum(II) Nitrat.',
        description: 'Kristal biru yang cantik tetapi berbahaya. Jika dipanaskan, ia terurai membebaskan gas Nitrogen Dioksida (NO₂) yang berwarna perang dan beracun.'
    },
    // --- CH3COOH Reactions ---
    {
        attackerFormula: 'CH₃COOH',
        defenderFormula: 'NaOH',
        reactionName: '16.Hot Ice Creation',
        equation: 'CH₃COOH + NaOH → CH₃COONa + H₂O',
        tcgEffect: 'Dapat Ais Panas.',
        description: 'Menghasilkan Natrium Asetat atau "Ais Panas". Larutan tepunya boleh membeku serta-merta apabila disentuh dan membebaskan haba (pad pemanas).'
    },
    {
        attackerFormula: 'CH₃COOH',
        defenderFormula: 'NH₃',
        reactionName: '17.Buffer Zone',
        equation: 'CH₃COOH + NH₃ → CH₃COONH₄',
        tcgEffect: 'Dapat Ammonium Asetat.',
        description: 'Garam dari asid lemah dan bes lemah. Sering digunakan untuk membuat larutan penimbal (buffer) bagi mengekalkan pH stabil.'
    },
    {
        attackerFormula: 'CH₃COOH',
        defenderFormula: 'Mg(OH)₂',
        reactionName: '18.De-Icer',
        equation: '2CH₃COOH + Mg(OH)₂ → Mg(CH₃COO)₂ + 2H₂O',
        tcgEffect: 'Dapat Magnesium Asetat.',
        description: 'Garam mesra alam yang digunakan sebagai pencair ais di jalan raya (de-icer), menggantikan garam klorida yang mengakis kereta.'
    },
    {
        attackerFormula: 'CH₃COOH',
        defenderFormula: 'Al(OH)₃',
        reactionName: '19.Astringent Mix',
        equation: '3CH₃COOH + Al(OH)₃ → Al(CH₃COO)₃ + 3H₂O',
        tcgEffect: 'Dapat Aluminium Asetat.',
        description: 'Juga dikenali sebagai larutan Burow. Ia bersifat astringen (mengecutkan tisu) dan digunakan untuk merawat gatal-gatal kulit.'
    },
    {
        attackerFormula: 'CH₃COOH',
        defenderFormula: 'Cu(OH)₂',
        reactionName: '20.Verdigris',
        equation: '2CH₃COOH + Cu(OH)₂ → Cu(CH₃COO)₂ + 2H₂O',
        tcgEffect: 'Dapat Kuprum(II) Asetat.',
        description: 'Menghasilkan pigmen hijau-biru bersejarah yang dipanggil "Verdigris". Digunakan dalam cat lukisan lama dan sebagai racun kulat.'
    },
    // --- Citric Acid Reactions ---
    {
        attackerFormula: 'C₆H₈O₇',
        defenderFormula: 'NaOH',
        reactionName: '21.Sour Salt',
        equation: 'C₆H₈O₇ + 3NaOH → Na₃Cit + 3H₂O',
        tcgEffect: 'Dapat Natrium Sitrat.',
        description: 'Garam masam-masin yang digunakan dalam minuman ringan (club soda) dan sebagai antikoagulan untuk menghalang darah daripada membeku.'
    },
    {
        attackerFormula: 'C₆H₈O₇',
        defenderFormula: 'NH₃',
        reactionName: '22.Rust Eater',
        equation: 'C₆H₈O₇ + 3NH₃ → (NH₄)₃Cit',
        tcgEffect: 'Dapat Ammonium Sitrat.',
        description: 'Agen pengkelat (chelating agent) yang kuat. Digunakan dalam industri untuk membuang karat (oksida besi) tanpa merosakkan logam asas.'
    },
    {
        attackerFormula: 'C₆H₈O₇',
        defenderFormula: '23.Mg(OH)₂',
        reactionName: 'Laxative Mix',
        equation: '2C₆H₈O₇ + 3Mg(OH)₂ → Mg₃(Cit)₂ + 6H₂O',
        tcgEffect: 'Dapat Magnesium Sitrat.',
        description: 'Garam magnesium yang sangat mudah diserap. Berfungsi sebagai ubat pencahar (laxative) masin untuk membersihkan usus sebelum pembedahan.'
    },
    {
        attackerFormula: 'C₆H₈O₇',
        defenderFormula: '24.Al(OH)₃',
        reactionName: 'Metal Complex',
        equation: 'C₆H₈O₇ + Al(OH)₃ → AlCit + 3H₂O',
        tcgEffect: 'Dapat Aluminium Sitrat.',
        description: 'Kompleks logam aluminium yang digunakan dalam produk kosmetik sebagai agen penegang kulit dan dalam sesetengah antipeluh.'
    },
    {
        attackerFormula: 'C₆H₈O₇',
        defenderFormula: 'Cu(OH)₂',
        reactionName: '25.Algae Killer',
        equation: '2C₆H₈O₇ + 3Cu(OH)₂ → Cu₃(Cit)₂ + 6H₂O',
        tcgEffect: 'Dapat Kuprum Sitrat.',
        description: 'Digunakan sebagai algaecide organik yang berkesan untuk membunuh lumut di kolam renang tanpa kesan sampingan sulfat.'
    },
    // --- SPECIAL / TRAP ---
    {
        attackerFormula: 'H₂O₂',
        defenderFormula: 'Mangkin',
        reactionName: '26.Rapid Decomposition',
        equation: '2H₂O₂ → 2H₂O + O₂',
        tcgEffect: 'Oksigen Tulen! Pulih 200 HP.',
        description: 'Eksperimen "Ubat Gigi Gajah"! Mangkin mempercepatkan penguraian hidrogen peroksida, membebaskan gas oksigen dan buih panas.'
    },
    {
        attackerFormula: 'C₆H₈O₇',
        defenderFormula: 'NaClO',
        reactionName: '27.Toxic Gas Release',
        equation: 'C₆H₈O₇ + 3NaClO → Cl₂ (Gas)',
        tcgEffect: 'BAHAYA! 300 DMG + Recoil.',
        description: 'JANGAN CAMPUR! Mencampurkan asid (walaupun asid lemah seperti sitrik) dengan peluntur membebaskan gas Klorin yang boleh membawa maut.'
    }
];

export const elementCards: Card[] = [
    {
        id: 'el-h',
        name: 'Hidrogen',
        symbol: 'H',
        type: 'Element',
        formula: 'H',
        description: 'Unsur paling ringan.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 1,
        rarity: 'Biasa',
        group: 1,
        period: 1,
        origin: 'Greek "hydro" (air) + "genes" (pembentuk).',
        scientificJustification: 'Unsur paling ringkas dan banyak di alam semesta. Bahan api bintang. Di Bumi, banyak dalam air (H₂O) dan bahan organik. No. Proton: 1, Jisim: 1.008 u.'
    },
    {
        id: 'el-c',
        name: 'Karbon',
        symbol: 'C',
        type: 'Element',
        formula: 'C',
        description: 'Asas organik.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 1,
        rarity: 'Biasa',
        group: 14,
        period: 2,
        origin: 'Latin "carbo" (arang batu).',
        scientificJustification: 'Asas hidupan organik. Membentuk rantaian panjang. Wujud juga sebagai Intan (keras) dan Grafit (lembut). No. Proton: 6, Jisim: 12.011 u.'
    },
    {
        id: 'el-o',
        name: 'Oksigen',
        symbol: 'O',
        type: 'Element',
        formula: 'O',
        description: 'Agen pengoksidaan.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 1,
        rarity: 'Biasa',
        group: 16,
        period: 2,
        origin: 'Greek "oxys" (asid) + "genes" (pembentuk).',
        scientificJustification: 'Penting untuk pernafasan/pembakaran. 21% atmosfera. Sangat reaktif. No. Proton: 8, Jisim: 15.999 u.'
    },
    {
        id: 'el-n',
        name: 'Nitrogen',
        symbol: 'N',
        type: 'Element',
        formula: 'N',
        description: 'Asas Ammonia.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 1,
        rarity: 'Tidak Biasa',
        group: 15,
        period: 2,
        origin: 'Greek "nitron" (soda) + "genes".',
        scientificJustification: '78% atmosfera. Stabil (ikatan ganda tiga). Penting untuk protein/DNA. No. Proton: 7, Jisim: 14.007 u.'
    },
    {
        id: 'el-na',
        name: 'Natrium',
        symbol: 'Na',
        type: 'Element',
        formula: 'Na',
        description: 'Logam alkali.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 1,
        rarity: 'Tidak Biasa',
        group: 1,
        period: 3,
        origin: 'Latin "natrium", Mesir "netjerj" (soda).',
        scientificJustification: 'Logam lembut, reaktif (terutama air). Dalam garam laut (NaCl). Penting untuk saraf. No. Proton: 11, Jisim: 22.990 u.'
    },
    {
        id: 'el-mg',
        name: 'Magnesium',
        symbol: 'Mg',
        type: 'Element',
        formula: 'Mg',
        description: 'Logam alkali bumi.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 1,
        rarity: 'Biasa',
        group: 2,
        period: 3,
        origin: 'Greek "Magnesia" (daerah di Greece).',
        scientificJustification: 'Logam ringan, bakar nyalaan putih terang. Pusat molekul klorofil. No. Proton: 12, Jisim: 24.305 u.'
    },
    {
        id: 'el-al',
        name: 'Aluminium',
        symbol: 'Al',
        type: 'Element',
        formula: 'Al',
        description: 'Logam Amfoterik.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 2,
        rarity: 'Langka',
        group: 13,
        period: 3,
        origin: 'Latin "alumen" (garam pahit).',
        scientificJustification: 'Paling banyak di kerak bumi. Ringan, tahan karat. Amfoterik. No. Proton: 13, Jisim: 26.982 u.'
    },
    {
        id: 'el-s',
        name: 'Sulfur',
        symbol: 'S',
        type: 'Element',
        formula: 'S',
        description: 'Asas sulfat.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 1,
        rarity: 'Langka',
        group: 16,
        period: 3,
        origin: 'Latin "sulphurium".',
        scientificJustification: 'Pepejal kuning rapuh. Bau telur tembelang (sebatian). Gunung berapi. No. Proton: 16, Jisim: 32.06 u.'
    },
    {
        id: 'el-cl',
        name: 'Klorin',
        symbol: 'Cl',
        type: 'Element',
        formula: 'Cl',
        description: 'Halogen.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 1,
        rarity: 'Tidak Biasa',
        group: 17,
        period: 3,
        origin: 'Greek "chloros" (hijau pucat).',
        scientificJustification: 'Gas pengoksida kuat, beracun. Disinfektan. Garam (NaCl). No. Proton: 17, Jisim: 35.45 u.'
    },
    {
        id: 'el-cu',
        name: 'Kuprum',
        symbol: 'Cu',
        type: 'Element',
        formula: 'Cu',
        description: 'Logam peralihan.',
        eCost: 0,
        mCost: 0,
        power: 0,
        tier: 1,
        rarity: 'Langka',
        group: 11,
        period: 4,
        origin: 'Latin "cuprum" (Cyprus).',
        scientificJustification: 'Logam merah, konduktor elektrik. Gangsa. Antimikrob. No. Proton: 29, Jisim: 63.546 u.'
    }
];

export const sintesisCards: Card[] = [
    // --- ACIDS ---
    {
        id: 'sin-hcl',
        name: 'Asid Hidroklorik',
        type: 'Sintesis',
        sintesisType: 'Asid',
        formula: 'HCl',
        description: 'Asid kuat. 150 DMG.',
        eCost: 3,
        mCost: 2,
        power: 150,
        tier: 0, // T0: Strongest
        rarity: 'Biasa',
        pH: 1.0,
        scientificJustification: 'Asid kuat monoprotik yang terurai sepenuhnya dalam air untuk melepaskan ion hidrogen dan klorida. Ia adalah komponen utama asid gastrik dalam perut manusia, membantu pencernaan dan membunuh bakteria.',
        molecularStructure: 'Linear H-Cl',
        dailyUsage: 'Digunakan secara meluas dalam industri untuk membersihkan keluli (pickling), memproses kulit, dan sebagai bahan kimia asas dalam penghasilan PVC. Di rumah, ia dikenali sebagai "spirit of salts" untuk membersihkan jubin.',
        requirements: [{ element: 'H', count: 1 }, { element: 'Cl', count: 1 }]
    },
    {
        id: 'sin-h2so4',
        name: 'Asid Sulfurik',
        type: 'Sintesis',
        sintesisType: 'Asid',
        formula: 'H₂SO₄',
        description: 'Asid diprotik kuat. 250 DMG.',
        eCost: 4,
        mCost: 4,
        power: 250,
        tier: 0, // T0: Strongest
        rarity: 'Langka',
        pH: 0.5,
        scientificJustification: 'Asid mineral yang sangat kuat, berminyak, dan bersifat higroskopik (menyerap air). Ia adalah agen pendehidratan yang kuat dan boleh menghanguskan bahan organik seperti gula dan kulit serta-merta.',
        molecularStructure: 'Tetrahedral S',
        dailyUsage: 'Bahan kimia industri yang paling banyak dihasilkan di dunia. Kegunaan utamanya adalah dalam pembuatan baja (superfosfat), elektrolit dalam bateri asid-plumbum kereta, dan penapisan petroleum.',
        requirements: [{ element: 'H', count: 2 }, { element: 'S', count: 1 }, { element: 'O', count: 4 }]
    },
    {
        id: 'sin-ch3cooh',
        name: 'Asid Asetik',
        type: 'Sintesis',
        sintesisType: 'Asid',
        formula: 'CH₃COOH',
        description: 'Asid Lemah. 80 DMG.',
        eCost: 1,
        mCost: 2,
        power: 80,
        tier: 2, // T2: Weakest
        rarity: 'Biasa',
        pH: 2.4,
        scientificJustification: 'Asid karboksilik lemah yang memberikan rasa masam dan bau tajam kepada cuka. Dalam larutan akueus, ia hanya terurai separa, menjadikannya selamat untuk dimakan dalam kepekatan rendah.',
        molecularStructure: 'Kumpulan Karboksil',
        dailyUsage: 'Paling biasa ditemui sebagai cuka masakan (biasanya 4-8% asid asetik). Ia digunakan sebagai pengawet makanan (jeruk), perasa, dan agen pembersih mesra alam untuk menanggalkan kerak kapur.',
        requirements: [{ element: 'C', count: 2 }, { element: 'O', count: 2 }, { element: 'H', count: 4 }]
    },
    {
        id: 'sin-citric',
        name: 'Asid Sitrik',
        type: 'Sintesis',
        sintesisType: 'Asid',
        formula: 'C₆H₈O₇',
        description: 'Asid Lemah Poliprotik. 100 DMG.',
        eCost: 2,
        mCost: 3,
        power: 100,
        tier: 2, // T2: Weakest
        rarity: 'Tidak Biasa',
        pH: 3.2,
        scientificJustification: 'Asid organik lemah yang triprotik (mempunyai tiga ion H+). Ia wujud secara semula jadi dalam buah-buahan sitrus seperti lemon dan limau, memainkan peranan penting dalam Kitaran Krebs metabolisme sel.',
        molecularStructure: '3x Karboksil',
        dailyUsage: 'Digunakan secara meluas sebagai penambah rasa masam dalam minuman ringan dan gula-gula. Ia juga berfungsi sebagai pengawet semula jadi dan agen penimbal dalam kosmetik dan produk penjagaan diri.',
        requirements: [{ element: 'C', count: 3 }, { element: 'H', count: 4 }, { element: 'O', count: 3 }]
    },
    {
        id: 'sin-hno3',
        name: 'Asid Nitrik',
        type: 'Sintesis',
        sintesisType: 'Asid',
        formula: 'HNO₃',
        description: 'Asid Kuat/Pengoksida. 180 DMG.',
        eCost: 3,
        mCost: 3,
        power: 180,
        tier: 0, // T0: Strongest
        rarity: 'Biasa',
        pH: 1.2,
        scientificJustification: 'Asid mineral yang sangat mengakis dan juga agen pengoksidaan yang kuat. Ia boleh melarutkan kebanyakan logam (kecuali emas dan platinum) dan menukarkan kulit menjadi kuning (tindak balas xanthoproteic).',
        molecularStructure: 'Planar Trigonal',
        dailyUsage: 'Kegunaan utamanya adalah dalam penghasilan baja (ammonium nitrat). Ia juga penting dalam pembuatan bahan letupan (seperti TNT dan nitrogliserin), dan digunakan dalam seni goresan logam.',
        requirements: [{ element: 'H', count: 1 }, { element: 'N', count: 1 }, { element: 'O', count: 3 }]
    },
    {
        id: 'sin-h2o2',
        name: 'Hidrogen Peroksida',
        type: 'Sintesis',
        sintesisType: 'Asid',
        formula: 'H₂O₂',
        description: 'Ejen Pengoksida. 120 DMG.',
        eCost: 2,
        mCost: 2,
        power: 120,
        tier: 2,
        rarity: 'Tidak Biasa',
        pH: 4.5,
        scientificJustification: 'Cecair biru pucat yang sedikit lebih likat daripada air. Ia adalah asid yang sangat lemah tetapi merupakan agen pengoksidaan yang kuat. Ia tidak stabil dan terurai perlahan-lahan kepada air dan oksigen.',
        molecularStructure: 'Buku Terbuka',
        dailyUsage: 'Biasa digunakan di rumah sebagai antiseptik ringan untuk luka dan sebagai agen pemutih untuk rambut atau gigi. Dalam industri, ia digunakan untuk melunturkan kertas dan pulpa, serta dalam rawatan air sisa.',
        requirements: [{ element: 'H', count: 2 }, { element: 'O', count: 2 }]
    },
    {
        id: 'sin-naoh',
        name: 'Natrium Hidroksida',
        type: 'Sintesis',
        sintesisType: 'Bes',
        formula: 'NaOH',
        description: 'Bes Kuat. Pulih 150 HP.',
        eCost: 3,
        mCost: 1,
        power: 150,
        tier: 0, // T0: Strongest
        rarity: 'Biasa',
        pH: 14.0,
        scientificJustification: 'Juga dikenali sebagai soda kaustik. Ia adalah bes kuat yang sangat larut dalam air dan membebaskan banyak haba. Ia bersifat deliquescent (menyerap kelembapan udara sehingga larut).',
        molecularStructure: 'Ionik Na+ OH-',
        dailyUsage: 'Bahan aktif utama dalam pencuci longkang dan ketuhar kerana keupayaannya melarutkan lemak dan gris (saponifikasi). Juga digunakan secara meluas dalam pembuatan sabun buku dan kertas.',
        requirements: [{ element: 'Na', count: 1 }, { element: 'O', count: 1 }, { element: 'H', count: 1 }]
    },
    {
        id: 'sin-nh3',
        name: 'Ammonia',
        type: 'Sintesis',
        sintesisType: 'Bes',
        formula: 'NH₃',
        description: 'Bes lemah. Pulih 80 HP.',
        eCost: 2,
        mCost: 2,
        power: 80,
        tier: 1.5, // T1.5: Weak-Medium
        rarity: 'Tidak Biasa',
        pH: 11.6,
        scientificJustification: 'Gas tidak berwarna dengan bau yang sangat tajam. Walaupun ia bes lemah, ia sangat larut dalam air membentuk ammonium hidroksida. Ia bertindak balas dengan asid untuk membentuk garam ammonium.',
        molecularStructure: 'Piramid trigonal',
        dailyUsage: 'Paling banyak digunakan dalam pembuatan baja nitrogen. Di rumah, larutan ammonia cair digunakan sebagai pembersih kaca dan permukaan kilat kerana ia menyejat tanpa meninggalkan kesan.',
        requirements: [{ element: 'N', count: 1 }, { element: 'H', count: 3 }]
    },
    {
        id: 'sin-mgoh2',
        name: 'Magnesium Hidroksida',
        type: 'Sintesis',
        sintesisType: 'Bes',
        formula: 'Mg(OH)₂',
        description: 'Antasid. Pulih 100 HP.',
        eCost: 2,
        mCost: 3,
        power: 100,
        tier: 1, // T1: Medium
        rarity: 'Biasa',
        pH: 10.5,
        scientificJustification: 'Bes lemah yang tidak larut sepenuhnya dalam air. Suspensi putihnya dalam air dikenali sebagai "Susu Magnesia". Ia meneutralkan asid tanpa meningkatkan pH secara berlebihan.',
        molecularStructure: 'Lapisan heksagon',
        dailyUsage: 'Digunakan secara meluas sebagai ubat antasid untuk melegakan pedih ulu hati dan senak perut, serta sebagai julap (laxative) ringan. Juga digunakan sebagai bahan kalis api dalam plastik.',
        requirements: [{ element: 'Mg', count: 1 }, { element: 'O', count: 2 }, { element: 'H', count: 2 }]
    },
    {
        id: 'sin-naclo',
        name: 'Natrium Hipoklorit',
        type: 'Sintesis',
        sintesisType: 'Bes',
        formula: 'NaClO',
        description: 'Bes Kuat. 200 DMG.',
        eCost: 4,
        mCost: 2,
        power: 200,
        tier: 3,
        rarity: 'Langka',
        pH: 12.0,
        scientificJustification: 'Garam bes yang tidak stabil dan merupakan agen pengoksidaan kuat. Dalam larutan, ia membebaskan asid hipoklorus yang berkesan membunuh bakteria dan memecahkan ikatan warna.',
        molecularStructure: 'Ionik',
        dailyUsage: 'Bahan aktif utama dalam peluntur pakaian (Clorox). Digunakan untuk memutihkan pakaian, membasmi kuman di permukaan rumah, dan merawat air kolam renang untuk membunuh alga dan bakteria.',
        requirements: [{ element: 'Na', count: 1 }, { element: 'Cl', count: 1 }, { element: 'O', count: 1 }]
    },
    {
        id: 'sin-nahco3',
        name: 'Natrium Bikarbonat',
        type: 'Sintesis',
        sintesisType: 'Bes',
        formula: 'NaHCO₃',
        description: 'Bes Lemah. Pulih 50 HP.',
        eCost: 1,
        mCost: 1,
        power: 50,
        tier: 1.5, // T1.5
        rarity: 'Biasa',
        pH: 8.3,
        scientificJustification: 'Garam asid yang bersifat amfoterik tetapi selalunya bertindak sebagai bes lemah. Ia terurai apabila dipanaskan melebihi 50°C, membebaskan gas karbon dioksida, air, dan natrium karbonat.',
        molecularStructure: 'Ionik',
        dailyUsage: 'Ejen penaik utama dalam pembuatan kek dan roti (membebaskan CO2 untuk menaikkan adunan). Juga digunakan sebagai ubat antasid, penyerap bau dalam peti sejuk, dan agen pemadam api serbuk kering.',
        requirements: [{ element: 'Na', count: 1 }, { element: 'H', count: 1 }, { element: 'C', count: 1 }, { element: 'O', count: 3 }]
    },
    {
        id: 'sin-na2co3',
        name: 'Natrium Karbonat',
        type: 'Sintesis',
        sintesisType: 'Bes',
        formula: 'Na₂CO₃',
        description: 'Bes Sederhana. Pulih 80 HP.',
        eCost: 2,
        mCost: 2,
        power: 80,
        tier: 1,
        rarity: 'Biasa',
        pH: 11.0,
        scientificJustification: 'Juga dikenali sebagai Soda Ash atau Soda Basuh. Ia adalah garam bes kuat asid lemah yang larut dalam air menghasilkan larutan beralkali sederhana. Ia meneutralkan asid dan memendakkan logam berat.',
        molecularStructure: 'Ionik',
        dailyUsage: 'Digunakan sebagai pelembut air dalam mencuci pakaian (mengikat ion magnesium dan kalsium). Juga bahan utama dalam pembuatan kaca, kertas, dan rayon, serta untuk menaikkan pH air kolam renang.',
        requirements: [{ element: 'Na', count: 2 }, { element: 'C', count: 1 }, { element: 'O', count: 3 }]
    },
    {
        id: 'sin-aloh3',
        name: 'Antasid (Al) (Aluminium Hidroksida)',
        type: 'Sintesis',
        sintesisType: 'Amfoterik',
        formula: 'Al(OH)₃',
        description: 'Amfoterik. Peneutral.',
        eCost: 2,
        mCost: 4,
        power: 0,
        tier: 2, // T2: Weakest
        rarity: 'Langka',
        pH: 7.5,
        scientificJustification: 'Hidroksida amfoterik, bermakna ia boleh bertindak balas sebagai asid (dengan bes kuat) atau sebagai bes (dengan asid kuat). Ia tidak larut dalam air, membentuk ampaian putih.',
        molecularStructure: 'Kompleks',
        dailyUsage: 'Digunakan sebagai ubat antasid untuk merawat simptom pedih ulu hati. Juga digunakan sebagai bahan tambah dalam vaksin (adjuvan) untuk meningkatkan tindak balas imun, dan sebagai bahan kalis api.',
        requirements: [{ element: 'Al', count: 1 }, { element: 'O', count: 3 }, { element: 'H', count: 3 }]
    },
    {
        id: 'sin-cuoh2',
        name: 'Kuprum(II) Hidroksida',
        type: 'Sintesis',
        sintesisType: 'Bes',
        formula: 'Cu(OH)₂',
        description: 'Bes Tak Larut.',
        eCost: 2,
        mCost: 2,
        power: 60,
        tier: 2, // T2: Weakest
        rarity: 'Langka',
        pH: 9.0,
        scientificJustification: 'Bes lemah berwarna biru pucat yang tidak larut dalam air. Ia tidak stabil secara haba dan akan terurai menjadi kuprum(II) oksida hitam jika dipanaskan perlahan-lahan.',
        molecularStructure: 'Kristal',
        dailyUsage: 'Digunakan sebagai alternatif kepada campuran Bordeaux (racun kulat dan nematisid) dalam pertanian. Juga digunakan sebagai pigmen biru dalam seramik dan cat, serta reagen dalam makmal.',
        requirements: [{ element: 'Cu', count: 1 }, { element: 'O', count: 2 }, { element: 'H', count: 2 }]
    },
];

export const garamCards: Card[] = [
    // HCl Salts
    {
        id: 'salt-nacl',
        name: 'Natrium Klorida',
        type: 'Garam',
        formula: 'NaCl',
        description: 'Elektrolit utama manusia.',
        effect: 'Pulih 50 HP.',
        eCost: 0, mCost: 0, power: 0, tier: 1, rarity: 'Biasa',
        scientificJustification: 'Garam dapur iairu garam neutral yang terbentuk daripada asid kuat (HCl) dan bes kuat (NaOH). Ia mempunyai struktur kekisi kristal kubik yang sangat stabil.',
        molecularStructure: 'Kubik Berpusat Muka',
        dailyUsage: 'Digunakan secara meluas sebagai perasa dan pengawet makanan. Dalam industri, ia adalah bahan mentah utama untuk menghasilkan klorin dan natrium hidroksida. Dalam perubatan, larutan salin digunakan untuk menggantikan cecair badan.',
        source: 'HCl + NaOH',
        isBuffer: false,
        reactionConfig: { type: 'heal', value: 50, description: 'Peneutralan lengkap. Selamat dan memulihkan.' }
    },
    {
        id: 'salt-nh4cl',
        name: 'Ammonium Klorida',
        type: 'Garam',
        formula: 'NH₄Cl',
        description: 'Garam meruap.',
        effect: 'Lawan buta 1 turn.',
        eCost: 0, mCost: 0, power: 0, tier: 1, rarity: 'Biasa',
        scientificJustification: 'Garam berasid yang terbentuk daripada asid kuat (HCl) dan bes lemah (NH₃). Ia mudah menyublim apabila dipanaskan, terurai kembali kepada gas ammonia dan hidrogen klorida.',
        molecularStructure: 'Kubik',
        dailyUsage: 'Digunakan sebagai elektrolit dalam bateri sel kering (sel Leclanché). Ia juga digunakan dalam fluks pateri untuk membersihkan oksida logam dan sebagai agen perasa dalam gula-gula "Salmiakki" di negara Nordic.',
        source: 'HCl + NH₃',
        isBuffer: false,
        reactionConfig: { type: 'status', statusName: 'Buta', description: 'Wap putih Salmiak menghalang penglihatan!' }
    },
    {
        id: 'salt-mgcl2',
        name: 'Magnesium Klorida',
        type: 'Garam',
        formula: 'MgCl₂',
        description: 'Penenang & Koagulan.',
        effect: 'Buang status negatif.',
        eCost: 0, mCost: 0, power: 0, tier: 1, rarity: 'Tidak Biasa',
        scientificJustification: 'Garam ionik yang sangat higroskopik (menyerap air dari udara). Ia wujud secara semula jadi dalam air laut.',
        molecularStructure: 'Kekisi Kristal',
        dailyUsage: 'Dikenali sebagai "Nigari" di Jepun, ia digunakan secara tradisional sebagai koagulan untuk membekukan susu soya menjadi tofu. Ia juga digunakan untuk mengawal habuk di jalan raya dan mencairkan ais pada suhu rendah.',
        source: 'HCl + Mg(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'heal', value: 30, description: 'Reaksi antasid menenangkan perut dan membuang status negatif.' }
    },
    {
        id: 'salt-alcl3',
        name: 'Aluminium Klorida',
        type: 'Garam',
        formula: 'AlCl₃',
        description: 'Ejen Pengering.',
        effect: 'Perisai 40 HP.',
        eCost: 0, mCost: 0, power: 0, tier: 1, rarity: 'Tidak Biasa',
        scientificJustification: 'Sebatian yang bertindak sebagai asid Lewis yang kuat. Dalam air, ia mengalami hidrolisis separa untuk menghasilkan larutan berasid dan membebaskan haba.',
        molecularStructure: 'Lapisan Oktahedral',
        dailyUsage: 'Bahan aktif utama dalam banyak produk antipeluh (deodoran) kerana ia membentuk palam gel dalam kelenjar peluh untuk mengurangkan peluh. Dalam industri kimia, ia adalah mangkin penting untuk tindak balas Friedel-Crafts.',
        source: 'HCl + Al(OH)₃',
        isBuffer: false,
        reactionConfig: { type: 'neutral', description: 'Membentuk lapisan pelindung antipeluh (Perisai +40).', value: 40 }
    },
    {
        id: 'salt-cucl2',
        name: 'Kuprum(II) Klorida',
        type: 'Garam',
        formula: 'CuCl₂',
        description: 'Api Hijau.',
        effect: '+50 Damage Api.',
        eCost: 0, mCost: 0, power: 50, tier: 2, rarity: 'Langka',
        scientificJustification: 'Garam logam peralihan yang paramagnetik. Warna kristalnya berubah dari coklat (kontang) ke biru-hijau (dihidrat) apabila menyerap kelembapan.',
        molecularStructure: 'Rantai Polimer',
        dailyUsage: 'Digunakan dalam piroteknik untuk menghasilkan warna api biru-hijau yang terang dalam bunga api. Ia juga digunakan sebagai mordan dalam pencelupan tekstil dan mangkin dalam sintesis organik.',
        source: 'HCl + Cu(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'damage', value: 50, description: 'Nyalaan hijau membakar! (50 DMG)' }
    },
    // H2SO4 Salts
    {
        id: 'salt-na2so4',
        name: 'Natrium Sulfat',
        type: 'Garam',
        formula: 'Na₂SO₄',
        description: 'Garam Glauber.',
        effect: '30 Splash Damage.',
        eCost: 0, mCost: 0, power: 30, tier: 1, rarity: 'Biasa',
        scientificJustification: 'Garam neutral yang sangat stabil secara kimia. Bentuk dekahidratnya dikenali sebagai Garam Glauber yang mempunyai kapasiti haba pendam yang tinggi.',
        molecularStructure: 'Monoklinik',
        dailyUsage: 'Digunakan secara besar-besaran sebagai bahan pengisi ("filler") dalam serbuk detergen pakaian rumah. Ia juga penting dalam proses Kraft untuk pembuatan pulpa kertas dan dalam pembuatan kaca untuk membuang buih udara.',
        source: 'H₂SO₄ + NaOH',
        isBuffer: false,
        reactionConfig: { type: 'damage', value: 30, description: 'Reaksi sangat eksotermik! Haba terbebas.' }
    },
    {
        id: 'salt-nh42so4',
        name: 'Ammonium Sulfat',
        type: 'Garam',
        formula: '(NH₄)₂SO₄',
        description: 'Baja Nitrogen.',
        effect: '+20 HP setiap giliran.',
        eCost: 0, mCost: 0, power: 0, tier: 1, rarity: 'Biasa',
        scientificJustification: 'Garam tak organik yang memberikan kedua-dua nitrogen dan sulfur kepada tumbuhan. Ia bersifat sedikit berasid apabila larut dalam tanah.',
        molecularStructure: 'Ortorombik',
        dailyUsage: 'Digunakan terutamanya sebagai baja untuk tanah beralkali. Ion ammonium dibebaskan dan membentuk sedikit asid, menurunkan pH tanah sambil membekalkan nitrogen penting untuk pertumbuhan tanaman.',
        source: 'H₂SO₄ + NH₃',
        isBuffer: false,
        reactionConfig: { type: 'heal', value: 20, description: 'Nutrien baja memulihkan tenaga.' }
    },
    {
        id: 'salt-mgso4',
        name: 'Magnesium Sulfat',
        type: 'Garam',
        formula: 'MgSO₄',
        description: 'Penenang Otot.',
        effect: 'Lawan -50% ATK.',
        eCost: 0, mCost: 0, power: 0, tier: 1, rarity: 'Tidak Biasa',
        scientificJustification: 'Magnesium sulfat heptahidrat atau dikeanli sebagai garam epsom yang sangat larut dalam air. Ia tidak mengubah pH tanah secara drastik berbanding pindaan lain.',
        molecularStructure: 'Kristal Jarum',
        dailyUsage: 'Terkenal sebagai garam mandian untuk melegakan sakit otot dan mengurangkan keradangan. Dalam pertanian, ia digunakan untuk merawat kekurangan magnesium dalam tumbuhan seperti tomato dan mawar.',
        source: 'H₂SO₄ + Mg(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'status', statusName: 'Weakness', description: 'Otot lawan menjadi tenang dan lemah.' }
    },
    {
        id: 'salt-also4',
        name: 'Aluminium Sulfat',
        type: 'Garam',
        formula: 'Al₂(SO₄)₃',
        description: 'Ejen Penggumpal.',
        effect: 'Bersihkan racun.',
        eCost: 0, mCost: 0, power: 0, tier: 2, rarity: 'Tidak Biasa',
        scientificJustification: 'Garam yang menghidrolisis dalam air membentuk mendakan gelatin aluminium hidroksida, yang memerangkap kotoran.',
        molecularStructure: 'Kristal Putih',
        dailyUsage: 'Digunakan secara meluas dalam loji rawatan air sebagai koagulan untuk menjernihkan air keruh (flokulasi). Juga digunakan oleh tukang kebun untuk menurunkan pH tanah bagi tumbuhan yang sukakan asid seperti Hydrangea.',
        source: 'H₂SO₄ + Al(OH)₃',
        isBuffer: false,
        reactionConfig: { type: 'heal', value: 0, description: 'Koagulasi membersihkan semua status racun!' }
    },
    {
        id: 'salt-cuso4',
        name: 'Kuprum(II) Sulfat',
        type: 'Garam',
        formula: 'CuSO₄',
        description: 'Racun Kulat.',
        effect: '+50% Damage Elektrik.',
        eCost: 1, mCost: 0, power: 50, tier: 2, rarity: 'Langka',
        scientificJustification: 'Garam kuprum pentahidrat deikenali juga sebagai Vitriol Biru yang berwarna biru terang. Ia bersifat toksik kepada mikroorganisma dan invertebrata.',
        molecularStructure: 'Triklinik',
        dailyUsage: 'Digunakan sebagai racun kulat dan algaecide dalam pertanian (campuran Bordeaux) dan kolam renang. Juga digunakan dalam penyaduran elektrik (electroplating) dan sebagai elektrolit dalam sel galvanik makmal.',
        source: 'H₂SO₄ + Cu(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'damage', value: 50, description: 'Sifat toksik menyebabkan kerosakan berterusan.' }
    },
    // HNO3 Salts
    {
        id: 'salt-nano3',
        name: 'Natrium Nitrat',
        type: 'Garam',
        formula: 'NaNO₃',
        description: 'Sendawa Chile.',
        effect: '+10% Damage Api.',
        eCost: 0, mCost: 0, power: 0, tier: 1, rarity: 'Biasa',
        scientificJustification: 'Garam nitrat yang sangat larut dan merupakan agen pengoksidaan yang kuat. Dikenali secara sejarah sebagai "Chile saltpeter".',
        molecularStructure: 'Trigonal',
        dailyUsage: 'Digunakan dalam baja untuk membekalkan nitrogen segera. Juga digunakan sebagai pengawet makanan (E251) dalam daging yang diproses untuk mengekalkan warna merah jambu dan dalam pembuatan kaca dan tembikar.',
        source: 'HNO₃ + NaOH',
        isBuffer: false,
        reactionConfig: { type: 'neutral', description: 'Pengoksida kuat meningkatkan potensi serangan api.' }
    },
    {
        id: 'salt-nh4no3',
        name: 'Ammonium Nitrat',
        type: 'Garam',
        formula: 'NH₄NO₃',
        description: 'Bahan Letupan.',
        effect: 'Perangkap Letupan (100 DMG).',
        eCost: 0, mCost: 0, power: 100, tier: 2, rarity: 'Langka',
        scientificJustification: 'Garam yang kaya dengan nitrogen. Ia tidak stabil pada suhu tinggi dan boleh meletup jika tercemar atau dipanaskan dengan tekanan.',
        molecularStructure: 'Kristal Putih',
        dailyUsage: 'Komponen utama dalam baja berkepekatan tinggi. Juga digunakan secara meluas dalam bahan letupan industri (ANFO) untuk perlombongan dan pembinaan kerana kosnya yang rendah dan kestabilannya.',
        source: 'HNO₃ + NH₃',
        isBuffer: false,
        reactionConfig: { type: 'damage', value: 100, description: 'BOOM! Reaksi letupan terjadi.' }
    },
    {
        id: 'salt-mgno32',
        name: 'Magnesium Nitrat',
        type: 'Garam',
        formula: 'Mg(NO₃)₂',
        description: 'Ejen Pengering.',
        effect: 'Keringkan (Lawan hilang 2M).',
        eCost: 0, mCost: 0, power: 0, tier: 1, rarity: 'Tidak Biasa',
        scientificJustification: 'Garam higroskopik yang sangat kuat, bermakna ia menyerap kelembapan dari udara dengan cepat.',
        molecularStructure: 'Kristal',
        dailyUsage: 'Digunakan dalam baja terutamanya untuk sistem hidroponik kerana kelarutannya yang tinggi. Juga digunakan sebagai agen pengering dalam proses industri dan dalam pembuatan asid nitrik pekat.',
        source: 'HNO₃ + Mg(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'status', statusName: 'Kering', description: 'Menyerap lembapan dan jisim lawan.' }
    },
    {
        id: 'salt-alno33',
        name: 'Aluminium Nitrat',
        type: 'Garam',
        formula: 'Al(NO₃)₃',
        description: 'Pengoksida.',
        effect: '+20 Damage.',
        eCost: 0, mCost: 0, power: 20, tier: 2, rarity: 'Tidak Biasa',
        scientificJustification: 'Agen pengoksidaan yang kuat dan sangat larut dalam air. Ia wujud biasanya sebagai nonahidrat.',
        molecularStructure: 'Kristal Putih',
        dailyUsage: 'Digunakan dalam penyamakan kulit, antipeluh, dan sebagai perencat kakisan. Ia juga digunakan dalam pengekstrakan uranium dan pembuatan teras pemanas untuk lampu pijar.',
        source: 'HNO₃ + Al(OH)₃',
        isBuffer: false,
        reactionConfig: { type: 'damage', value: 20, description: 'Pengoksidaan mengakis permukaan.' }
    },
    {
        id: 'salt-cuno32',
        name: 'Kuprum(II) Nitrat',
        type: 'Garam',
        formula: 'Cu(NO₃)₂',
        description: 'Gas Merah Beracun.',
        effect: 'Racun 40/giliran.',
        eCost: 0, mCost: 0, power: 40, tier: 2, rarity: 'Langka',
        scientificJustification: 'Pepejal kristal biru yang, apabila dipanaskan, terurai membebaskan gas Nitrogen Dioksida (NO₂) yang berwarna perang kemerahan dan beracun.',
        molecularStructure: 'Kristal Biru',
        dailyUsage: 'Digunakan dalam tekstil dan agen pengilat logam. Dalam makmal kimia organik, ia digunakan sebagai mangkin dan agen penitratan. Sering digunakan dalam demonstrasi sel voltan di sekolah.',
        source: 'HNO₃ + Cu(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'damage', value: 40, description: 'Gas NO2 beracun terbebas!' }
    },
    // CH3COOH Salts
    {
        id: 'salt-ch3coona',
        name: 'Natrium Asetat',
        type: 'Garam',
        formula: 'CH₃COONa',
        description: 'Penghabluran Haba.',
        effect: 'Bekukan Lawan (Stun).',
        eCost: 0, mCost: 0, power: 0, tier: 2, rarity: 'Langka',
        scientificJustification: 'Larutan tepu tepu natrium asetat boleh disejukkan di bawah takat bekunya tanpa memejal. Gangguan fizikal menyebabkan penghabluran serta-merta yang membebaskan haba (eksotermik).',
        molecularStructure: 'Kekisi Ionik',
        dailyUsage: 'Digunakan dalam pad pemanas tangan (hand warmers) yang boleh diguna semula. Juga digunakan sebagai perasa dalam kerepek kentang (rasa "salt & vinegar") dan sebagai pengawet konkrit.',
        source: 'CH₃COOH + NaOH',
        isBuffer: false,
        reactionConfig: { type: 'status', statusName: 'Stun', description: 'Penghabluran mengejut membekukan pergerakan.' }
    },
    {
        id: 'salt-ch3coonh4',
        name: 'Ammonium Asetat',
        type: 'Garam',
        formula: 'CH₃COONH₄',
        description: 'Penimbal pH.',
        effect: 'Kebal 1 Giliran.',
        eCost: 0, mCost: 0, power: 0, tier: 2, rarity: 'Tidak Biasa',
        scientificJustification: 'Garam yang terbentuk dari asid lemah dan bes lemah. Ia sering digunakan untuk membuat larutan penimbal (buffer) untuk mengekalkan pH.',
        molecularStructure: 'Kristal Putih',
        dailyUsage: 'Digunakan sebagai de-icer yang boleh terbiodegradasi (mesra alam) untuk jalan raya. Juga digunakan sebagai bahan tambah makanan untuk mengawal keasidan.',
        source: 'CH₃COOH + NH₃',
        isBuffer: true,
        bufferMultiplier: 0.15, // Good buffer but volatile
        reactionConfig: { type: 'heal', value: 0, description: 'Penimbal menstabilkan keadaan.' }
    },
    {
        id: 'salt-mgac2',
        name: 'Magnesium Asetat',
        type: 'Garam',
        formula: 'Mg(CH₃COO)₂',
        description: 'De-icer Mesra Alam.',
        effect: 'Buang status Beku.',
        eCost: 0, mCost: 0, power: 0, tier: 1, rarity: 'Biasa',
        scientificJustification: 'Garam higroskopik yang sangat larut dalam air dan alkohol.',
        molecularStructure: 'Monoklinik',
        dailyUsage: 'Digunakan sebagai alternatif kepada kalsium klorida untuk mencairkan ais di jalan raya kerana ia kurang mengakis. Juga digunakan dalam pencelupan tekstil dan percetakan.',
        source: 'CH₃COOH + Mg(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'neutral', description: 'Mencairkan kesan beku.', value: 0 }
    },
    {
        id: 'salt-alac3',
        name: 'Aluminium Asetat',
        type: 'Garam',
        formula: 'Al(CH₃COO)₃',
        description: 'Ubat Astringen.',
        effect: 'Lawan -20% ATK.',
        eCost: 0, mCost: 0, power: 0, tier: 2, rarity: 'Tidak Biasa',
        scientificJustification: 'Mempunyai sifat astringen yang kuat (mengecutkan tisu badan). Dikenali sebagai larutan Burow.',
        molecularStructure: 'Serbuk Putih',
        dailyUsage: 'Digunakan dalam perubatan dermatologi untuk merawat kerengsaan kulit seperti gigitan serangga, ruam, dan "athlete\'s foot" dengan mengurangkan keradangan dan kegatalan.',
        source: 'CH₃COOH + Al(OH)₃',
        isBuffer: false,
        reactionConfig: { type: 'status', statusName: 'Shrink', description: 'Astringen mengecutkan otot lawan.' }
    },
    {
        id: 'salt-cuac2',
        name: 'Kuprum(II) Asetat',
        type: 'Garam',
        formula: 'Cu(CH₃COO)₂',
        description: 'Verdigris.',
        effect: 'Kakisan Senjata (-10 ATK).',
        eCost: 0, mCost: 0, power: 0, tier: 2, rarity: 'Langka',
        scientificJustification: 'Sebatian berwarna biru-hijau pekat. Secara sejarah dikenali sebagai pigmen "Verdigris".',
        molecularStructure: 'Dimer',
        dailyUsage: 'Dahulu digunakan sebagai pigmen dalam cat lukisan. Kini digunakan sebagai racun kulat, racun serangga, dan sebagai mangkin dalam sintesis organik.',
        source: 'CH₃COOH + Cu(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'damage', value: 10, description: 'Kakisan merosakkan peralatan lawan.' }
    },
    // Citric Acid Salts
    {
        id: 'salt-citrate',
        name: 'Natrium Sitrat',
        type: 'Garam',
        formula: 'Na₃C₆H₅O₇',
        description: 'Pengawet Makanan.',
        effect: 'Halang Decay/Rot.',
        eCost: 0, mCost: 0, power: 0, tier: 2, rarity: 'Tidak Biasa',
        scientificJustification: 'Garam natrium asid sitrat yang mempunyai rasa masin dan sedikit masam. Ia bersifat alkali.',
        molecularStructure: 'Kompleks',
        dailyUsage: 'Digunakan sebagai bahan tambah makanan (E331) untuk rasa dan pengawet dalam minuman ringan (club soda). Dalam perubatan, ia digunakan sebagai antikoagulan (mencegah pembekuan darah) semasa pemindahan darah.',
        source: 'C₆H₈O₇ + NaOH',
        isBuffer: true,
        bufferMultiplier: 0.1, // Strong triprotic buffer
        reactionConfig: { type: 'heal', value: 20, description: 'Mengawet HP.' }
    },
    {
        id: 'salt-nh4cit',
        name: 'Ammonium Sitrat',
        type: 'Garam',
        formula: '(NH₄)₃C₆H₅O₇',
        description: 'Penghilang Karat.',
        effect: 'Pecah Perisai (Shield 0).',
        eCost: 0, mCost: 0, power: 0, tier: 2, rarity: 'Langka',
        scientificJustification: 'Agen pengkelat (chelating agent) yang berkesan mengikat ion logam.',
        molecularStructure: 'Kristal Putih',
        dailyUsage: 'Digunakan secara meluas dalam pembersihan industri untuk membuang karat (oksida besi) dan kerak daripada dandang logam tanpa merosakkan logam itu sendiri.',
        source: 'C₆H₈O₇ + NH₃',
        isBuffer: false,
        reactionConfig: { type: 'status', statusName: 'Break', description: 'Pengkelat memecahkan perisai logam.' }
    },
    {
        id: 'salt-mgcit',
        name: 'Magnesium Sitrat',
        type: 'Garam',
        formula: 'Mg₃(C₆H₅O₇)₂',
        description: 'Ubat Pencahar.',
        effect: 'Lawan buang 1 kad.',
        eCost: 0, mCost: 0, power: 0, tier: 2, rarity: 'Langka',
        scientificJustification: 'Garam magnesium yang mudah diserap oleh badan. Ia menarik air ke dalam usus melalui osmosis.',
        molecularStructure: 'Serbuk Putih',
        dailyUsage: 'Sangat biasa digunakan sebagai ubat julap (laxative) untuk merawat sembelit atau membersihkan usus sebelum pembedahan. Juga diambil sebagai suplemen magnesium.',
        source: 'C₆H₈O₇ + Mg(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'status', statusName: 'Flush', description: 'Kesan osmotik memaksa buang kad.' }
    },
    {
        id: 'salt-alcit',
        name: 'Aluminium Sitrat',
        type: 'Garam',
        formula: 'AlC₆H₅O₇',
        description: 'Kosmetik.',
        effect: '+1 Jisim (M).',
        eCost: 0, mCost: 0, power: 0, tier: 2, rarity: 'Biasa',
        scientificJustification: 'Kompleks logam aluminium dengan asid sitrat.',
        molecularStructure: 'Kompleks',
        dailyUsage: 'Digunakan dalam produk kosmetik sebagai agen penyaman kulit dan astringen. Ia membantu menegangkan kulit dan mengecilkan pori.',
        source: 'C₆H₈O₇ + Al(OH)₃',
        isBuffer: false,
        reactionConfig: { type: 'neutral', value: 0, description: 'Menegangkan struktur pertahanan.' }
    },
    {
        id: 'salt-cucit',
        name: 'Kuprum Sitrat',
        type: 'Garam',
        formula: 'Cu₃(C₆H₅O₇)₂',
        description: 'Pembunuh Alga.',
        effect: 'Racun Air (50 DMG).',
        eCost: 0, mCost: 0, power: 50, tier: 2, rarity: 'Langka',
        scientificJustification: 'Garam kuprum organik.',
        molecularStructure: 'Serbuk Hijau',
        dailyUsage: 'Digunakan sebagai algaecide untuk mengawal pertumbuhan alga di kolam renang dan takungan air. Juga digunakan sebagai suplemen pemakanan untuk kekurangan kuprum.',
        source: 'C₆H₈O₇ + Cu(OH)₂',
        isBuffer: false,
        reactionConfig: { type: 'damage', value: 50, description: 'Toksik kepada organisma akuatik.' }
    }
];

export const tacticalCards: Card[] = [
    { id: 'tac-cat', name: 'Mangkin', symbol: 'CAT', type: 'Taktikal', description: 'Kurangkan Kos Sintesis (-2E).', eCost: 0, mCost: 0, power: 0, rarity: 'Tidak Biasa', scientificJustification: 'Mangkin merendahkan tenaga pengaktifan tindak balas.' },
];
